"""Print a CSV as a fixed-width table, sized for a terminal recording.

Generic recipe-layer helper: do not edit this file per project. It knows
nothing about any particular piece — you choose the columns on the command
line, from the tape.

    python demo/lib/preview.py out/products.csv sku name price
    python demo/lib/preview.py out/rejects.csv --rows 8 --cell 28
    python demo/lib/preview.py feed.csv sku vendor --collapse

Why this exists: the first portfolio piece wrote a one-off version of it, the
second did not need one, and the next two both do — a before/after of a CSV is
the whole story in a terminal clip. Writing it a third time would have been a
fork of a thing that was never project-specific in the first place.

Two rules it follows, because a demo that lies is worse than no demo:

  * A capped table says how many rows it did not show, so nobody reads six
    rows as "the file has six rows".
  * A column that is not in the file is an error naming the ones that are,
    not a silently blank column that looks fine on camera.

Options:
  --rows N     rows to show before the "and N more" footer   (default 6)
  --cell N     truncate any cell wider than N characters     (default 34)
  --collapse   drop a row that is identical to the one above it, for a file
               that repeats parent-level fields across child rows
  --no-count   suppress the footer (use when the cap is above the row count
               anyway and you want the last line to be data)
"""

from __future__ import annotations

import csv
import sys

DEFAULT_ROWS = 6
DEFAULT_CELL = 34
ELLIPSIS = "…"


def parse_args(argv: list[str]) -> tuple[str, list[str], int, int, bool, bool]:
    path = ""
    columns: list[str] = []
    rows, cell = DEFAULT_ROWS, DEFAULT_CELL
    collapse, count = False, True

    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--rows":
            rows = int(argv[i + 1])
            i += 2
        elif arg == "--cell":
            cell = int(argv[i + 1])
            i += 2
        elif arg == "--collapse":
            collapse, i = True, i + 1
        elif arg == "--no-count":
            count, i = False, i + 1
        elif arg.startswith("--"):
            raise SystemExit(f"preview: unknown option {arg}")
        elif not path:
            path, i = arg, i + 1
        else:
            columns.append(arg)
            i += 1

    if not path:
        raise SystemExit(__doc__.strip().splitlines()[0])
    return path, columns, rows, cell, collapse, count


def clip(value: str, width: int) -> str:
    value = " ".join(value.split())  # newlines inside a cell would break the grid
    if len(value) <= width:
        return value
    return value[: width - 1] + ELLIPSIS


def is_numeric(value: str) -> bool:
    return bool(value) and value.lstrip("-+").replace(".", "", 1).replace(",", "").isdigit()


def render(header: list[str], body: list[list[str]]) -> list[str]:
    table = [header] + body
    widths = [max(len(row[i]) for row in table) for i in range(len(header))]
    # Right-align a column only if every value in it is a number, so prices and
    # counts line up on the decimal point without dragging text columns along.
    right = [
        all(is_numeric(row[i]) for row in body) if body else False
        for i in range(len(header))
    ]

    def line(row: list[str]) -> str:
        cells = [
            cell.rjust(w) if right[i] else cell.ljust(w)
            for i, (cell, w) in enumerate(zip(row, widths))
        ]
        return "  ".join(cells).rstrip()

    return [line(header), "  ".join("-" * w for w in widths)] + [line(r) for r in body]


def main(argv: list[str]) -> int:
    path, columns, max_rows, max_cell, collapse, show_count = parse_args(argv)

    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = reader.fieldnames or []
        rows = list(reader)

    if not fieldnames:
        print(f"{path} is empty")
        return 0

    if columns:
        missing = [c for c in columns if c not in fieldnames]
        if missing:
            print(
                f"preview: {path} has no column {', '.join(missing)}. "
                f"It has: {', '.join(fieldnames)}",
                file=sys.stderr,
            )
            return 2
    else:
        columns = list(fieldnames)

    selected: list[list[str]] = []
    consumed = 0
    for row in rows:
        consumed += 1
        cells = [clip(row.get(c) or "", max_cell) for c in columns]
        # A collapsed row is not hidden — the row above it is standing in for
        # it — so it counts as consumed and never reaches the footer.
        if collapse and selected and cells == selected[-1]:
            continue
        selected.append(cells)
        if len(selected) == max_rows:
            break

    for line in render(columns, selected):
        print(line)

    remaining = len(rows) - consumed
    if show_count and remaining > 0:
        print(f"... and {remaining} more rows ({len(rows)} total)")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
